### ISSUE TITLE
>what is a model?

### ISSUE THREAD

**Issue by Mrinal18** [Mrinal18/NFL_Kaggle#13]
>How to  select a model?
>Reading research papers . To find which model best suites our data?( Do not go with good model go for better  model ? )
> Documentation for model selection ><

**Comment by Mrinal18** [comment]
@gsvsumanth please add your ideas here.

**Comment by gsvsumanth** [comment]
https://everitt257.github.io/post/2018/08/10/object_detection.html

**Comment by gsvsumanth** [comment]
https://towardsdatascience.com/faster-r-cnn-a-step-towards-real-time-object-detection-98c186732a69

**Comment by gsvsumanth** [comment]
> well, you are trying to maintain the higher accuracy and reduce complexity. Faster RCNN is using VGG as a backbone model and is a two-stage object detector i.e. RPN and VGG while YOLO(Darknet backbone) is a single shot detector utilizing anchor boxes. one possible combination is to try using Darknet in faster RCNN replacing VGG and vice versa for YOLO. the other possible option is to remove RPN and utilize anchor boxes similar to YOLO in faster RCNN.
> But again, it depends on your problem. what kind of dataset you want to use. like YOLO results are extremely bad on the self-driving cars dataset.

This is for real time detection

**Comment by Mrinal18** [comment]
@gsvsumanth please close this issue if there's nothing more to add.
